name: Build and Release Linux App Image

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build Binary
        run: |
          mvn clean package -Plinux
          mkdir -p dist
          tar -czf dist/StudentEditor-linux-x64.tar.gz -C build/linux-binary/ StudentEditor
          echo "Binary tar.gz OK"

      - name: Build AppImage
        run: |
          mvn package -Plinux-app-image
          mkdir -p dist
          cp build/linux-app-image/StudentEditor.AppImage dist/
          echo "AppImage OK"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
           name: linux-build-artifacts
           path: dist/

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install WiX Toolset
        run: choco install wixtoolset --no-progress -y

      - name: Install Maven
        run: choco install maven --no-progress -y

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build Binary
        run: mvn clean package -Pwindows

      - name: Build Windows Package
        run: mvn clean package -Pwindows-package

      - name: Copy artifacts
        run: |
          mkdir dist
          powershell Compress-Archive -Path build\windows-binary\StudentEditor\* -DestinationPath dist\StudentEditor_portable.zip
          copy build\windows-packages\StudentEditor-1.0.exe dist\StudentEditor_installer.exe
          echo "Windows artifacts OK"

      - name: List artifacts
        run: |
          echo "=== Conteúdo da pasta dist ==="
          dir dist

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-build-artifacts
          path: dist\


  release:
    needs: [build-linux, build-windows]
    runs-on: ubuntu-latest
    steps:
      - name: Download Linux artifacts
        uses: actions/download-artifact@v4
        with:
          name: linux-build-artifacts
          path: dist/

      - name: Download Windows artifacts
        uses: actions/download-artifact@v4
        with:
          name: windows-build-artifacts
          path: dist/

      - name: List release files
        run: ls -la dist/

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "build-${{ github.run_id }}-${{ github.run_attempt }}"
          name: "Build ${{ github.run_number }} - ${{ github.sha }}"
          body: |
            Automated build from main branch
            Commit: ${{ github.sha }}
            Date: ${{ github.event.head_commit.timestamp }}
            Workflow Run: ${{ github.run_id }} (Attempt: ${{ github.run_attempt }})
          files: |
            dist/*.AppImage
            dist/*.tar.gz
            dist/*.exe
            dist/*.zip
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}